/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface Cv1xvancoaAmbulanceWlList {
    }
}
declare global {
    interface HTMLCv1xvancoaAmbulanceWlListElement extends Components.Cv1xvancoaAmbulanceWlList, HTMLStencilElement {
    }
    var HTMLCv1xvancoaAmbulanceWlListElement: {
        prototype: HTMLCv1xvancoaAmbulanceWlListElement;
        new (): HTMLCv1xvancoaAmbulanceWlListElement;
    };
    interface HTMLElementTagNameMap {
        "cv1xvancoa-ambulance-wl-list": HTMLCv1xvancoaAmbulanceWlListElement;
    }
}
declare namespace LocalJSX {
    interface Cv1xvancoaAmbulanceWlList {
    }
    interface IntrinsicElements {
        "cv1xvancoa-ambulance-wl-list": Cv1xvancoaAmbulanceWlList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "cv1xvancoa-ambulance-wl-list": LocalJSX.Cv1xvancoaAmbulanceWlList & JSXBase.HTMLAttributes<HTMLCv1xvancoaAmbulanceWlListElement>;
        }
    }
}
